### ISSUE TITLE
Make a tag/release for PyHEP 2022 "proceedings"

### ISSUE THREAD

**Issue by eduardo-rodrigues** [gradhep/examples#2]
Hello @phinate, can you kindly prepare the tag/release so that I then use it to mint a DOI on Zenodo and attach it to the workshop "proceedings" https://zenodo.org/communities/pyhep2022? Advance thanks.

**Comment by matthewfeickert** [comment]
@phinate I think you're already familiar with minting Zenodo DOIs for your code, but if I'm wrong c.f. https://github.com/matthewfeickert/pyhep-notebook-talk-example#zenodo-dois.

**Comment by phinate** [comment]
Done, thanks! https://zenodo.org/record/7129991

**Comment by eduardo-rodrigues** [comment]
You just need to "attach it" to the community https://zenodo.org/communities/pyhep2022/ to be part of the proceedings. Else it is a "random" entry in Zenodo. I get a ping to curate and we're done :-). Thanks.
